PersoonSearchFormPagination linting and bugfix
lblod/frontend-loket pull request #140
Opened 2022-07-25 09:15 UTC by Poltergeistz

When triggering a search with Zoek Voornaam and browsing above page 1, if an other search is triggered with input Familienaam, `this.currentPage` shouldn't keep the previous value.

This is causing errors and missleads the user (e.g The vorige button shouldn't be displayed as the page is 0 but since `this.currentPage` is keeping values from the first search this is the expected result). 

![Page 2 - Loket voor lokale besturen](https://user-images.githubusercontent.com/38471754/180734510-512f71a0-1ee9-4531-8208-28b49c6352a3.png)

![Page 1 - Loket voor lokale besturen](https://user-images.githubusercontent.com/38471754/180731600-05c42de6-43d5-4bdc-aeca-2da0cd03d5cd.png)

- Resolves the todo no-action.

- PersoonSearchFormPagination linter fix.

- `this.currentPage` fix

2022-07-25 11:46 UTC, Windvis requested changes
Left some small remarks.

Thanks for working on the Octane refactoring! :tada:

2022-07-25 11:46 UTC, Windvis commented on app/components/shared/persoon/persoon-search-form-pagination.js
> +  classNames = ['data-table-pagination'];
classNames isn't used anymore in Glimmer components since it doesn't add an implicit wrapping div.

This worked like this in classic components:

```hbs
<div class="data-table-pagination">
{{! rest of the template that's visible in the persoon-form-pagination.hbs file}}
</div>
```

So to make the Octane version match the Ember component version that wrapping div should be added to the template file. If it doesn't affect the styling it might not be needed, but I would still delete the `classNames` property since it doesn't do anything anymore.

2022-07-25 11:46 UTC, Windvis commented on app/components/shared/persoon/persoon-search-form-pagination.js
> +  }
Can be removed since it's not used.

2022-07-25 11:46 UTC, Windvis commented on app/components/shared/persoon/persoon-search-form-pagination.js
> +      if (this.args.links.self.number !== this.args.page) return 1;
As mentioned in the chat, I think the real fix is to let the PersoonSearchForm component reset the page to 0 when it triggers a new search. That way this component will receive the new value as an argument and the template should rerender.

2022-07-25 12:42 UTC, Poltergeistz commented on app/components/shared/persoon/persoon-search-form-pagination.js
> +  classNames = ['data-table-pagination'];
Made the change, looks like it makes no difference with or without the class. I'm going to remove it.

2022-07-26 07:40 UTC, Windvis approved these changes

2022-07-26 07:41 UTC, merged