Feature/new product
lblod/frontend-loket pull request #143
Opened 2022-07-27 11:26 UTC by Asergey91

adds a button to create an empty product/service
service pr:

2022-07-27 12:03 UTC, Windvis commented
I assume the linting issues are caused by the target branch so we can ignore that for now.

2022-07-27 12:50 UTC, Asergey91 commented on app/components/public-services/details-page.js
> +        this.hasUnsavedChanges = false;
yep thats specifically for that, didnt know it was an issue

2022-07-27 12:50 UTC, Asergey91 commented on app/templates/public-services/index.hbs
> +      @route="public-services.add"
yep sry

2022-07-27 13:33 UTC, Asergey91 commented
> I assume the linting issues are caused by the target branch so we can ignore that for now.

yep, something about triple curly brackets

2022-07-27 15:04 UTC, Windvis approved these changes

2022-07-28 11:40 UTC, cecemel requested changes

2022-07-28 11:40 UTC, cecemel commented on app/templates/public-services/index.hbs
> +      Product toevoegen
Can you make 'Volledig nieuw product toevoegen'?

2022-07-28 11:40 UTC, cecemel commented on app/templates/public-services/index.hbs
> +    <AuButton
The button is on the wrong page; should be where they can select templates

2022-07-29 05:16 UTC, merged