added a fix for validations running on page load
lblod/frontend-loket pull request #153
Opened 2022-08-05 09:08 UTC by Asergey91

this fixes an issue where fields with the rdfa editor were validated on page load (unlike other fields)

2022-08-05 09:14 UTC, cecemel commented
@Windvis to clarify: It seems the editor throws focusOut events after init. This is an issue in the editor that needs investigating. 
This codes should prevent the validation occurs immediately after load

2022-08-05 09:14 UTC, cecemel commented
@Asergey91 perhaps in code, you can explain this too

2022-08-05 09:20 UTC, Windvis commented
@cecemel Thanks for the info, I was just going to ask about that 😄.

Although, instead of fixing the `focusOut` event being triggered I think the real fix is that the editor provides a proper "The content was updated" event which we can use to trigger the update, which according to [this comment](https://github.com/lblod/ember-submission-form-fields/pull/78#discussion_r884822520) seems to be on the roadmap already?

2022-08-05 09:23 UTC, cecemel commented
@Windvis yeah indeed that would be a better abstraction. Could you perhaps open the discussion on the chat (#core-editor)?

2022-08-05 09:52 UTC, cecemel requested changes

2022-08-05 09:52 UTC, cecemel commented on app/components/rdf-form-fields/rich-text-editor.js
> +      // hack to prevent validations from firing on page load
Can you just elaborate a bit: because issue in editor, will need to fixed on that level. (So we know in the future a bit more about the why? rather than the what/how?)
In my opinion comment should first tackle the why? and if needed (because complex algorithm on the what/how)

2022-08-05 09:52 UTC, cecemel commented
@Windvis if @Asergey91 fixes my last comment, I am ok with merge. You?

2022-08-05 09:53 UTC, Windvis commented
Yes, sure! We don't really have any other options at the moment I think 😄.

2022-08-05 13:04 UTC, Windvis commented
We discussed this issue a bit in the Rocket.Chat and while there now is a event we can use to detect content changes it seems it still has some issues which prevents us from using it here. We'll merge this as a temporary fix for now.

2022-08-08 07:36 UTC, Windvis commented on app/components/rdf-form-fields/rich-text-editor.js
> +        super.updateValue(editorValue);
I wonder, would it also make sense to compare the new value with the old one before triggering the update? If we combine that with the `@stealFocus={{false}}` argument I think it covers most false positives?

I did some debugging to find out why some editors were still being focused and it seems to be caused by the browser APIs that are used to write the data to the DOM. So not something that is (easily) fixable I guess.

Comparing the values should prevent the case where a user clicks the editor to trigger an update as well.

2022-08-11 11:52 UTC, Windvis commented on app/components/rdf-form-fields/rich-text-editor.js
> +        super.updateValue(editorValue);
I went with this approach. With the previous version it was possible to miss content changes due to the `firstRun` check. If for some reason the `focusOut` event wasn't triggered on init for an editor instance, and the user added actual content, the `firstRun` was still set to true so the update would be skipped. By comparing the current value to the old one we sidestep that issue.

2022-08-11 11:53 UTC, Windvis commented
I force pushed to this branch since I rebased on dev. If you have the previous version checked out you will need to reset it to the origin version.

2022-08-11 11:54 UTC, Windvis commented on app/components/rdf-form-fields/rich-text-editor.js
> +    }
Not strictly needed since we do the value comparison anyways, but it seemed like unnecessary work for the editor.

2022-08-12 13:06 UTC, Asergey91 commented
uhm it doesnt seem to load the data into the editor on my machine anymore.
on page reload all editor instances are blank even though im sure those fields are filled in.

2022-08-12 13:10 UTC, Windvis commented
Yikes, it seemed to work when I tried it 😄. I'll check after the demo.

2022-08-12 13:14 UTC, Windvis commented on app/components/rdf-form-fields/rich-text-editor.js
> +    this.value = '';
It's this 😄, must have made a last minute change without testing. Sorry, my bad.

2022-08-12 15:13 UTC, Windvis commented on app/components/rdf-form-fields/rich-text-editor.js
> +    this.value = '';
Should be fixed now.

2022-08-16 12:55 UTC, Asergey91 commented
looks good

2022-08-17 08:34 UTC, merged