change status on save
lblod/frontend-loket pull request #163
Opened 2022-08-22 10:10 UTC by Asergey91

2022-08-22 10:40 UTC, Asergey91 commented
@felix the status concepts that were being used for publicservice.status are the same ones as publicservice.lifecycleStatus i tried to find a more appropriate concept scheme but no luck, should I make a new concept scheme?

@Windvis i tried to make the forms readonly but no luck... what should I pass to rdfaForm?

2022-08-22 10:47 UTC, Windvis commented
> @Windvis i tried to make the forms readonly but no luck... what should I pass to rdfaForm?

@Asergey91  I think you can simply set the `@show` argument of the RdfForm component based on the status value? 

Similar to how it's done in the ember-submission-form-fields test app: https://github.com/lblod/ember-submission-form-fields/blob/9c4cd929ac6ecdee08b0f0fbba4014180e4d7e7f/tests/dummy/app/components/test-form.hbs#L7

2022-08-22 11:22 UTC, Asergey91 commented
> > @Windvis i tried to make the forms readonly but no luck... what should I pass to rdfaForm?
> 
> @Asergey91 I think you can simply set the `@show` argument of the RdfForm component based on the status value?
> 
> Similar to how it's done in the ember-submission-form-fields test app: https://github.com/lblod/ember-submission-form-fields/blob/9c4cd929ac6ecdee08b0f0fbba4014180e4d7e7f/tests/dummy/app/components/test-form.hbs#L7

ah but that breaks the rdfaEditor

2022-08-22 13:44 UTC, Asergey91 commented
https://github.com/lblod/ember-submission-form-fields/pull/98

2022-08-22 14:37 UTC, Windvis requested changes

2022-08-22 14:37 UTC, Windvis commented on app/components/rdf-form-fields/rich-text-editor.hbs
> +  {{#if this.value}}
This will hide the visual "content" and only show the label which looks a bit weird to me. Why is this check needed exactly? If it's something quirky with `{{{this.value}}}` I would only conditionally render that so we show at least an empty looking "input"?

If the "empty input" looks weird as well we could maybe use the `<ValueWithPlaceholder>` component to show a `-` if there is no value.

```hbs
          <ValueWithPlaceholder @value={{this.value}}>
            <:value as |value|>
              <div class="rich-text-editor-content">
                {{! template-lint-disable no-triple-curlies}}
                {{{value}}}
             </div>
            </:value>
          </ValueWithPlaceholder>
```

2022-08-22 14:37 UTC, Windvis commented on app/utils/constants.js
> +  'cd0b5eba-33c1-45d9-aed9-75194c3728d3': 'inhoud',
Also this config is highly specific to the component, so I wouldn't move it out of there. The generic config that _could_ be extracted is the uuid of the form. We could in theory reuse these ids in the tab routes then but for now I would simply keep it in the component as before.

2022-08-22 14:37 UTC, Windvis commented on app/components/public-services/details-page.js
> +    return statusUri !== LIFECYCLE_STATUS.CONCEPT;
`LIFECYCLE_STATUS` doesn't exist anymore so I think this throws?

2022-08-23 11:15 UTC, Asergey91 commented on app/components/rdf-form-fields/rich-text-editor.hbs
> +  {{#if this.value}}
it looked wierd to me imho, but i dont mind changing it back

2022-08-23 11:19 UTC, Windvis commented on app/components/rdf-form-fields/rich-text-editor.hbs
> +  {{#if this.value}}
Yea, agreed. This is probably just something that Dieter needs to look at.

2022-08-23 11:32 UTC, Windvis approved these changes

2022-08-24 10:53 UTC, merged