Fix duplicate entries in the mandate position select
lblod/frontend-loket pull request #187
Opened 2022-09-07 10:58 UTC by Poltergeistz

DL-4163

We get all IDs when not selecting a bestuursperiode, leading to duplicate results when we call `mandaat?filter[bevat-in][id]={IDs}&sort=bestuursfunctie.label`.

This changes the order of entities inside the `BestuursperiodenSelector` so the recent date is set first.

When a user isn't selecting a bestuursperiode and wants to create a new mandatee, the bestuursperiode by default is the most recent on the `new` route.

2022-09-07 12:12 UTC, claire-lovisa requested changes
Removing the `reverse()` impacts the behaviour of the `bestuursperioden-selector` on other pages such as the Mandatenbeheer of non-worship admin units, which often have periods in the past. I feel like it's weird that we have the first period it time as a default one.

![removing-reverse-impacts-other-modules](https://user-images.githubusercontent.com/23281659/188874991-b83a7cbe-d651-4619-ab7c-e5a8a88d375a.png)

@cecemel what's your opinion ? It's indeed better for worship services but makes it weird for the other unit types. Should we just keep the reverse and hide organen that are in the future ?

2022-09-07 12:12 UTC, claire-lovisa commented on app/routes/eredienst-mandatenbeheer/new.js
> +        this.store.findAll('half-election'),
The half-elections got removed in #184 , this is breaking the flow no ?

2022-09-08 14:40 UTC, cecemel commented
@claire-lovisa @Poltergeistz 
I the less confusing would be, i.e. default behaviour (so if none selected)
- select the bestuursorgaan matching the period where we are in today
-  if none is found, take the next starting one in the future?
-?

2022-09-15 14:06 UTC, cecemel commented
Closing because fixed in #196

2022-09-15 14:06 UTC, closed without merging