Prevent to save a `mandataris` without a `mandaat`
lblod/frontend-loket pull request #206
Opened 2022-09-26 18:23 UTC by Poltergeistz

This sets a check when creating a new `mandataris`.
The user **must** select a `mandaat` from the selector to create a new `mandataris`.

UX Improvements to be made ?

- `Verplicht` pill for mandaat label.
- Error handling to inform the user.

2022-09-27 11:24 UTC, Windvis requested changes
I would also do the UX suggestions you already mentioned. It should be fairly simple.

- show the required pill in the label
- show an error message
- show a red border on the select. This would also need a new `@error` argument which would should the correct error state on the select.

2022-09-27 11:24 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/new.js
> +    if (this.shouldSelectMandaat) {
I would use an async util for this instead. That way the state can simply be derived from the mandatee record so we don't need to keep a custom flag here.

```suggestion
    if (shouldSelectMandaat(worshipMandatee)) {
```

The util could then simply check if the mandate relationship is set.

2022-09-27 11:24 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/new.js
> +      return {}; // Room for some error handling
I would add an error to the `worshipmandatee` record, similar to how we did it for the contact information.

something like (Pseudo) `worshipMandatee.errors.add('mandate', 'Dit veld is verplicht')`

We can then show this error in the template.

2022-09-28 10:16 UTC, Poltergeistz commented on app/controllers/eredienst-mandatenbeheer/new.js
> +      worshipMandatee.errors.add('mandaat', 'Mandaat is een vereist veld.');
Is it better to move this line into the util function ? 
Something like `if (!mandate) worshipMandatee.errors.add('mandaat', 'Mandaat is een vereist veld.');`

2022-09-28 10:20 UTC, Poltergeistz commented on app/templates/eredienst-mandatenbeheer/new.hbs
> +        <AuLabel for="mandaat" @error={{showError}} @required={{true}}>Mandaat</AuLabel>
Unrelated to this PR but I've noticed in the FP that the mandaat startDate is also mandatory.
Does it makes sense to handle this now or it's not top priority ?

2022-09-28 10:40 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/new.js
> +      worshipMandatee.errors.add('mandaat', 'Mandaat is een vereist veld.');
Oh, I think it's ok like this for now? It might make sense if we add more validations, but in that case we should turn it into a "validate" method which would add the errors after which we could check the `isValid` property on the record.

2022-09-28 10:40 UTC, Windvis commented on app/templates/eredienst-mandatenbeheer/new.hbs
> +        <AuLabel for="mandaat" @error={{showError}} @required={{true}}>Mandaat</AuLabel>
It might make sense. I would double check with @cecemel if it should happen now though.

2022-09-28 10:47 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/new.js
> +      worshipMandatee.errors.add('mandaat', 'Mandaat is een vereist veld.');
The first string should be the name of the attribute or relationship (so that would be 'bekleedt' here). It has the benefit that the error message will be cleared if the value changes. Except... It seems that isn't working for relationships at the moment 😄 (which might be a bug in Ember Data). Maybe it's related to the inheritance, not sure.

```suggestion
      worshipMandatee.errors.add('bekleedt', 'Mandaat is een vereist veld.');
```

I would still clear the error message if the user selects a value after the message is shown. For now I would explicitly [remove](https://api.emberjs.com/ember-data/4.7/classes/Errors/methods/remove?anchor=remove) it in the 'setMandate' action.

2022-09-28 10:53 UTC, Poltergeistz commented on app/controllers/eredienst-mandatenbeheer/new.js
> +      worshipMandatee.errors.add('mandaat', 'Mandaat is een vereist veld.');
Yes I think it's ok too. Just checking :slightly_smiling_face:

2022-09-28 11:24 UTC, Windvis approved these changes

2022-09-28 11:50 UTC, merged