Missing mandatory fields
lblod/frontend-loket pull request #213
Opened 2022-10-03 10:51 UTC by Poltergeistz

DL-4291

This address the changes requested from testing :

- adding the field `geboorte` as required for the `create-persoon` component, also handling error if the field is empty.
- adding `startDatum` & `Functienaam` as required for the New page in `bedienarenbeheer`, same for error handling.

Note : Thinking about the `Rijksregisternummer`, since it does display the birth date at the beginning. Will this be tested to compare/check if the **date from the Rijksregisternummer** = **geboorteDatum** ?

Does fields must be mandatory too on `Edit` page ? if so, this also needs to be added in `eredienst-mandatenbeheer`.

2022-10-07 08:20 UTC, cecemel commented
> Note : Thinking about the `Rijksregisternummer`, since it does display the birth date at the beginning. Will this be tested in the future to compare/check if the **date from the Rijksregisternummer** = **geboorteDatum** ?

I wouldn't do this, many exceptions in reality for this rule

2022-10-07 08:28 UTC, Poltergeistz commented
> > Note : Thinking about the `Rijksregisternummer`, since it does display the birth date at the beginning. Will this be tested in the future to compare/check if the **date from the Rijksregisternummer** = **geboorteDatum** ?
> 
> I wouldn't do this, many exceptions in reality for this rule

Okay thanks, I was just wondering

2022-10-07 08:34 UTC, cecemel commented
> Does fields must be mandatory too on `Edit` page ? if so, this also needs to be added in `eredienst-mandatenbeheer`

yeah will have to be required here too

2022-10-10 12:23 UTC, Windvis requested changes

2022-10-10 12:23 UTC, Windvis commented on app/components/shared/persoon/create-persoon.hbs
> +          @required={{true}}
As mentioned during the plannings meeting, this should be conditional based on some argument.

2022-10-10 13:06 UTC, Poltergeistz commented on app/models/worship-mandatee.js
> +    worshipMandatee.errors.add('bekleedt', 'mandaat is een vereist veld.');
Okay

2022-10-10 13:06 UTC, Poltergeistz commented on app/components/shared/persoon/create-persoon.hbs
> +          @required={{true}}
Okay, I'll have to check where it's not required but I assume it is in worship modules so not required by default on other modules ?

2022-10-10 13:07 UTC, Poltergeistz commented on app/controllers/worship-ministers-management/minister/edit.js
> +        minister.ministerPosition // this is a workaround when no functies are set
Yes I agree, but the issue is when you have empty fields on load (which shouldn't happen anymore I think) it will be `.isValid = true` which is a problem as it wont trigger the error and save as it is. I'll make the change to see what it triggers again to be sure but I think I was encountering some errors with relationship states. `root.loaded.saved became invalid` or something I can't remember. I'll test that and see.

2022-10-10 14:06 UTC, Poltergeistz commented on app/controllers/eredienst-mandatenbeheer/new.js
> +        worshipMandatee.start &&
Ok, after testing, I remember the flow now. It's when you try to save with only the starting date provided, you end up with this error.
```
Uncaught Error: Attempted to handle event `didCommit` on <worship-mandatee:6344256EE6092A8AA7318272> while in state root.loaded.created.invalid.
```
The field `mandaat` is triggered as error but the form is saved anyway with a blank field and does the POST request without redirecting.

2022-10-10 14:12 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/new.js
> +        worshipMandatee.start &&
We might be running into Ember Data bugs again then, or a different underlying issue. I would try to find the root cause and if we can't find it add a comment why the check is needed. At the moment it looks like an implementation oversight 😄.

2022-10-10 14:31 UTC, Poltergeistz commented on app/controllers/eredienst-mandatenbeheer/new.js
> +        worshipMandatee.start &&
Yeah, I'll dig that but I think it's likely to be an ember data bug. 

I agree this is not very elegant and we might have to refactor this `save` generator function as it will become a cognitive pain to maintain with all this conditionals statement.

2022-10-11 14:21 UTC, Poltergeistz commented on app/controllers/eredienst-mandatenbeheer/new.js
> +        worshipMandatee.start &&
Thanks for testing, I appreciate the explanation.

2022-10-13 11:08 UTC, Windvis approved these changes

2022-10-13 11:47 UTC, Windvis commented
I think this is ready to be merged but some merge conflicts need to be resolved now.

2022-10-13 13:22 UTC, Poltergeistz commented
This should resolve the conflicts

2022-10-13 13:34 UTC, merged