Shouldn't select and save an endDate that is less or equal than the starting date
lblod/frontend-loket pull request #217
Opened 2022-10-12 11:50 UTC by Poltergeistz

DL-4375

This prevent to save the record if the ending date is less or equal than the starting date for `eredienst-mandatenbeheer` and `bedienarenbeheer`. Sending en error to the user if it's the case.

2022-10-12 13:44 UTC, Windvis requested changes

2022-10-12 13:44 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
> +    if (this.model.einde <= this.model.start) {
This will throw false positives in some cases. For example if the end date is cleared it will show the warning. I think this check is only needed if both the start and end date are a date object?

 But it's probably better to validate this before saving, similar to the other validations?

2022-10-12 13:44 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
> +        'De einddatum moet groter zijn dan de begindatum'
I'm not sure about the error message but I'm not the best writer. Maybe something like this: 'De einddatum moet na de startdatum liggen'

2022-10-12 13:44 UTC, Windvis commented on app/templates/worship-ministers-management/minister/edit.hbs
> +        <AuLabel for="worship-minister-correction-end-date" @error={{showError}}>Eindedatum</AuLabel>
Whoops, I just noticed a typo. It should be `Einddatum` instead of `Eindedatum`.

2022-10-12 16:45 UTC, Poltergeistz commented
https://github.com/lblod/frontend-loket/pull/217/commits/907452a0d7a29bd61d00164281ab7eecf1f300ae Should remove the case when the date is empty since it's not mandatory to have an end date filled in the FP

2022-10-13 11:13 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
> +    if (this.model.einde <= this.model.start) {
I just noticed that we need to clear the error in some cases. For example:

- choose a start date
- choose an end date that comes before it (or is the same)
- an error message will be shown
- change the start date to a date that comes before the end date
- the error message isn't cleared since the end date field value wasn't changed

2022-10-13 13:47 UTC, Windvis approved these changes

2022-10-13 13:51 UTC, merged