`create-persoon` component: rijksregisternummer UX improvements
lblod/frontend-loket pull request #222
Opened 2022-10-17 14:28 UTC by Poltergeistz

DL-4385

This autocomplete the following fields when `rrn` is provided : 

- Geboortedatum
- Geslacht

Handling errors cases on save for now.

2022-10-17 15:11 UTC, Windvis requested changes

2022-10-17 15:11 UTC, Windvis commented on app/components/shared/persoon/create-persoon.js
> +  }
We should also check if the rijksregisternummer is valid before doing all the birthdate and gender checking. It will throw a lot of exceptions otherwise.

Also there are edge cases where dates of birth and genders aren't known when the RRN is created so we should check for that first before setting the corresponding values. The library has the `isGenderKnown` and `isBirthDateKnown` utils for that.

2022-10-18 08:19 UTC, Poltergeistz commented on app/components/shared/persoon/create-persoon.js
> +    }
I was hesitant to put this actually, I can remove it.

2022-10-18 08:25 UTC, Poltergeistz commented on app/utils/rijksregisternummer.js
> +}
I don't know, I don't see any license so it's hard to tell. I guess a clear mention of the repo and the owner is needed.

2022-10-18 09:13 UTC, Poltergeistz commented on app/components/shared/persoon/create-persoon.js
>      if (!this.isValidRijksregisternummer) {
Indeed.

2022-10-18 09:59 UTC, Poltergeistz commented on app/components/shared/persoon/create-persoon.js
> +  }
It seems there is more errors showing up when I'm trying to test the case where there is no gender or no birth date. I tried to generate a rrn but the website does not offer the option to remove either the date or the gender.

2022-10-18 14:30 UTC, Windvis commented on app/components/shared/persoon/create-persoon.js
> +          ? getBirthDate(this.rijksregisternummer)
I think this needs to be an actual Date instance since the `loadOrCreateGeboorte` method expects it to be one. I think just wrapping it in a `new Date(getBirthDate(this.rijksregisternummer))` should work.

Alternatively we could do it in the util itself, but I think keeping that logic where it's needed is better. The string version has the advantage that we don't have to mess with timezones if that isn't needed.

2022-10-18 14:37 UTC, Windvis commented on app/utils/rijksregisternummer.js
> +  const { birthDate, serial } = parse(nrn);
Nitpick: I would move this below the first checks since it's only needed at the end of the util.

2022-10-18 14:37 UTC, Windvis commented on app/utils/rijksregisternummer.js
> +  if (isBisNumber(nrn)) return false;
I'm not sure about this? I think bis numbers are still valid RRNs, no?

2022-10-18 14:37 UTC, Windvis commented on app/utils/rijksregisternummer.js
> +    parseInt(nrn.slice(9, 11)) ===
The parse util also returns the checksum, so we can reuse that here I think
```suggestion
    parseInt(checksum) ===
```

And then retrieve that from the parse util:
`const { birthDate, serial, checksum } = parse(nrn);`

2022-10-18 15:24 UTC, Poltergeistz commented on app/components/shared/persoon/create-persoon.js
> +      this.rijksregisternummer = rijksregisternummer;
Yes `rijksregisternummer` must be a string or we get errors.

2022-10-18 15:25 UTC, Windvis commented on app/components/shared/persoon/create-persoon.js
> +      this.rijksregisternummer = rijksregisternummer;
Yes, but it will always be one already? The input event will return an empty string if no data was entered.

2022-10-18 15:28 UTC, Poltergeistz commented on app/utils/rijksregisternummer.js
> +  if (isBisNumber(nrn)) return false;
Well me too, I'm not familiar with this. I though BIS and RRN are two different things.

2022-10-18 15:29 UTC, Poltergeistz commented on app/utils/rijksregisternummer.js
> +    parseInt(nrn.slice(9, 11)) ===
Indeed :+1:

2022-10-18 15:35 UTC, Windvis commented on app/utils/rijksregisternummer.js
> +  if (isBisNumber(nrn)) return false;
I would just drop that check and keep the same behavior as the previous getter. I'm not 100% sure what the BIS numbers are, but it sounds like it's some sort of temporary RRN (but still a valid one).

2022-10-18 15:48 UTC, Poltergeistz commented on app/utils/rijksregisternummer.js
> +  if (isBisNumber(nrn)) return false;
The issue I encounter was when you enter a RRN with month above 20 or 40 (That's actually a BIS number then), it can be valid and could return an error where the date is not ISO formatted (e.g. the month = 14)

2022-10-18 15:50 UTC, Windvis commented on app/utils/rijksregisternummer.js
> +  if (isBisNumber(nrn)) return false;
But then the `isBirthDateKnown` util would return false I think?

2022-10-18 16:04 UTC, Poltergeistz commented on app/utils/rijksregisternummer.js
> +  if (isBisNumber(nrn)) return false;
Now yes but previously it wasn't the case from the original function.

2022-10-18 16:46 UTC, Poltergeistz commented
After some testing it looks like the person is created with empty values.

2022-10-20 13:53 UTC, merged