[Bedienarenbeheer] Show an error message if no contact info is provided when creating or editing position
lblod/frontend-loket pull request #231
Opened 2022-11-10 09:25 UTC by Poltergeistz

DL-4463

This shows an error message when the required contact information is missing or unselected.

2022-11-10 10:59 UTC, Windvis requested changes

2022-11-10 11:23 UTC, Poltergeistz commented on app/templates/worship-ministers-management/new.hbs
> +      {{#unless (or this.isEditingContactPoint isSelected)}}
Yes we could do that, that would solve the lint error.

Minor issue, when we enter the route new, `contacts` query is fetching for the contact info but it passes this check : 
```
      if (contacts.length === 1) {
        this.selectedContact = contacts.firstObject;
      }
```
Even if contacts is empty it will have a length of 1. I remember doing something like contacts.content.length to check the content of the response but I wonder if there is a better way to do it, because this.selectedContact is not really true.

2022-11-10 11:23 UTC, Poltergeistz commented on app/templates/worship-ministers-management/new.hbs
> +            Contactgegevens zijn verplicht. Klik op "Contactgegevens" om contactgegevens in te vullen of selecteer een bestaande contactgegevens.
Thanks, yes it will give more hints to the user indeed.

2022-11-10 11:52 UTC, Windvis commented on app/templates/worship-ministers-management/new.hbs
> +      {{#unless (or this.isEditingContactPoint isSelected)}}
Very strange, I wouldn't expect it to behave like that 🤔. How do I test that? Select a person that doesn't have any positions yet?

2022-11-10 13:47 UTC, Poltergeistz commented on app/templates/worship-ministers-management/new.hbs
> +      {{#unless (or this.isEditingContactPoint isSelected)}}
Sorry, I tested again you're right it's `0`. But I don't understand when I log this.selectedContacts I have 
```
Object { store: {…}, _internalModel: {…}, currentState: {…}, isError: false, adapterError: null, _super: ROOT(), _getDeprecatedEventedInfo: _getDeprecatedEventedInfo()
, Symbol("OWNER"): {…}, Symbol("INIT_FACTORY"): {…} }
 true
```
The steps were : 
- Select a person (I named First person for the example) that does not have contacts in the `contact-information-table` Then click on bedienarenbeheer breadcrumb to leave the page. **Expected to be undefined.**
- Select a person that has contacts in the `contact-information-table`. Then click on bedienarenbeheer breadcrumb to leave the page. **Expected to have data.**
- Now select First person again. **Expected to be undefined**

Does the logs have the same code as above or it's null or undefined ? I suspect that this.selectedContact is not reset and keep the old values.

2022-11-10 14:09 UTC, Windvis commented on app/templates/worship-ministers-management/new.hbs
> +      {{#unless (or this.isEditingContactPoint isSelected)}}
Aha, good catch. I think this line is the issue: https://github.com/lblod/frontend-loket/blob/326d5d054d69f2b99dc6c63d8fd96cd53a183b25/app/routes/worship-ministers-management/new.js#L50

`this.selectedContact` is still the value from the previous route since we set the value conditionally. If the route has no contacts, `this.selectedContact` will not be updated. On the edit page this isn't an issue since we always set `this.selectedContact` there (and it's set to `undefined` sometimes).

I'm usually not the biggest fan of storing state on the route instance for this reason, but it was done that way already and everything seemed to be working so I didn't mention it before.

As an alternative we could use the transition to store the selected contact instead. That way we won't have to deal with stale state since we receive a new transition each time.

The [model hook](https://api.emberjs.com/ember/4.8/classes/Route/methods/model?anchor=model) receives the transition instance as the second argument.

The [transition](https://api.emberjs.com/ember/4.8/classes/Transition/properties/data?anchor=data) instance itself has a data property which we can use to store custom data.

[`setupController`](https://api.emberjs.com/ember/4.8/classes/Route/methods/setupController?anchor=setupController) receives the transition as the third argument, so we can then read out the value there.

So in pseudo it could look like this:
```js
model(params, transition) {
 //...
  if (contacts.length === 1) {
    transition.data.selectedContact = contacts.firstObject;
  }
 // ...
}

setupController(controller, model, transition) {
  //...
  controller.selectedContact = transition.data.selectedContact;
}
```

2022-11-10 14:42 UTC, Poltergeistz commented on app/templates/worship-ministers-management/new.hbs
> +      {{#unless (or this.isEditingContactPoint isSelected)}}
Indeed that was the line.

2022-11-10 14:44 UTC, Windvis commented on app/templates/worship-ministers-management/new.hbs
> +      {{#unless (or this.isEditingContactPoint isSelected)}}
Also, that seems like a bug that is unrelated to this PR so I wouldn't include a fix for it here, if possible.

2022-11-10 16:52 UTC, Windvis commented on app/templates/worship-ministers-management/new.hbs
> +      {{#unless (or this.isEditingContactPoint isSelected)}}
Sure 👍.

2022-11-10 17:12 UTC, Windvis requested changes

2022-11-10 17:12 UTC, Windvis commented on app/controllers/worship-ministers-management/minister/edit.js
> +    } else if (contacts.length > 0) {
I don't think this needs to be a separate if check. The else block should be fine. In there we can then check which variant of the error message we should show.

2022-11-10 17:12 UTC, Windvis commented on app/controllers/worship-ministers-management/minister/edit.js
> +        'Selecteer een van de bestaande contactgegevens.'
We can check the `contacts.length` here and show the correct error message based on that.

2022-11-10 17:12 UTC, Windvis commented on app/controllers/worship-ministers-management/new.js
> +      worshipMinister.errors.add(
We probably need the `becomeDirty` hack here as well?

2022-11-10 17:12 UTC, Windvis commented on app/controllers/worship-ministers-management/minister/edit.js
> +      minister.errors.remove('contacts');
This is no longer needed if it's moved to the top.

2022-11-10 17:36 UTC, Poltergeistz commented on app/controllers/worship-ministers-management/new.js
> +      worshipMinister.errors.add(
It works on new without it but that's maybe because the relationship doesn't exist yet ?

2022-11-14 09:09 UTC, Windvis approved these changes

2022-11-14 09:09 UTC, merged