[Bedienarenbeheer / Eredienst-Mandatenbeheer] Allow addresses outside of Flanders
lblod/frontend-loket pull request #240
Opened 2022-12-01 13:34 UTC by Poltergeistz

2022-12-05 09:08 UTC, Windvis commented
The issue you are seeing could also be this one: https://github.com/emberjs/ember-inspector/issues/1898

2022-12-05 09:42 UTC, Poltergeistz commented
> The issue you are seeing could also be this one: [emberjs/ember-inspector#1898](https://github.com/emberjs/ember-inspector/issues/1898)
> 
> It's supposedly already fixed, but the fixes were done in Ember Data and Ember itself, so we probably need to update.

Did not think about this issue, this looks similar. But when I log for the created record I should access the value of this `newAdres.straatnaam` ?

```
newAdres = this.store.createRecord('adres', adres);
console.log('newAdres', newAdres.straatnaam);
```

I have undefined as a result it looks like the record is created without the `adres` payload even if it got data in it. 

I tried to save a minister and indeed the address attributes fields are just undefined. Might be an async/await issue ?

2022-12-05 16:08 UTC, Windvis commented on app/models/adres.js
> +    'gemeentenaam',
I would map these to either the label values or simply use a generic `Dit veld is verplicht` message instead.

At the moment it looks a bit strange since some labels don't match the property names and they are lowercased. It also only works because it uses Dutch words as properties instead of English ones.

2022-12-05 16:12 UTC, Windvis commented on app/models/adres.js
> +  });
I wouldn't use `setProperties` here. That only works because the Model class still extends classic EmberObject somewhere in the chain, but that's being phased out. I would simply set each property explicitly in the vanilla js way. 
```js
address.busnummer = null;
address.huisnummer = null;
// ...
```

Alternatively I think [`attributes`](https://api.emberjs.com/ember-data/4.7/classes/Model/properties/attributes?anchor=attributes) can be used to loop over all attributes and set it to `null` that way.

2022-12-05 16:31 UTC, Windvis commented on app/models/adres.js
> +  });
This feels very strange to me. It seems we simply want to nullify _some_ attributes, but not all? What's the reasoning behind that? In any case, only nullifying the attributes that need it seems better to me. I would then also give the function a more descriptive name since "updateAddressAttributes" is very generic and doesn't describe what it does.

2022-12-05 16:36 UTC, Windvis commented on app/utils/empty-string-to-null.js
> +export function setEmptyStringsToNull(changeset) {
We're not using changesets so I assume this was copied from OP?

Also, I think the intention is to not serialize the empty strings so there aren't any "empty" triples in the database. If so I think this logic is better suited in the Ember Data serializer.

2022-12-05 16:44 UTC, Windvis commented on app/utils/empty-string-to-null.js
> +  let properties = Object.keys(changeset.toJSON());
`toJSON` is deprecated and it will be removed in v4: https://deprecations.emberjs.com/ember-data/v3.x#toc_record-toJSON

Since I'm trying hard to get the app ready for v4, I wouldn't introduce new deprecated code 😄.

2022-12-05 16:52 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
> +  async handleInputToggle() {
(I'll try to review this method tomorrow, but I wanted to post the current remarks already.)

2022-12-06 08:40 UTC, Poltergeistz commented on app/components/contact-information-table/input-manual-address.hbs
> +  <AuInput @disabled={{true}}/>
I can enable it, I can't remember why I did this in the first place maybe because of the dropdown in the design.

2022-12-06 08:43 UTC, Poltergeistz commented on app/models/adres.js
> +    'gemeentenaam',
Yes I agree, I can go with the generic one.

2022-12-06 08:45 UTC, Poltergeistz commented on app/models/adres.js
> +  });
I think we wont need this function if I replace it with 
```
address.adresRegisterId = null;
address.adresRegisterUri = null;
```

The logic was : 

When we're editing addresses that are selected, it maps the fields in the `manual-input-address` component so the uri and id needs to be removed only if the address is been edited otherwise it will result in duplicates. Right now, if we enter manual mode it will set those attributes to `null` but I think we want a trigger (Like an actual change of any property to nullify the props ?).

2022-12-06 08:46 UTC, Poltergeistz commented on app/utils/empty-string-to-null.js
> +  let properties = Object.keys(changeset.toJSON());
Ah sorry :confused: I will change this

2022-12-06 08:48 UTC, Poltergeistz commented on app/utils/empty-string-to-null.js
> +export function setEmptyStringsToNull(changeset) {
Yes, okay.

2022-12-06 08:49 UTC, Poltergeistz commented on app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
> +  async handleInputToggle() {
Thanks for the review :smiley:

2022-12-06 08:52 UTC, Poltergeistz commented on app/models/adres.js
> +  });
Agreed, plus I would delete this function as it's not called in any file now.

2022-12-06 10:17 UTC, Poltergeistz commented on app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
> +  @tracked isManualAddress = false;
In `addNewContact` since the record is new it wont have any `adresRegisterUri`. So it will trigger manual input mode, is it what we want by default instead of selecting an address from the selector ?

2022-12-06 10:22 UTC, Windvis requested changes

2022-12-06 10:22 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
> +  async handleInputToggle() {
I'm not sure about this whole method logic to be honest. Is this how it was implemented in OP? Was this behavior discussed somewhere?

I'll have to look into it some more, but I think it can be simplified on first sight.

2022-12-06 10:41 UTC, Poltergeistz commented on app/components/contact-information-table/input-manual-address.hbs
> +  >
I use Prettier but sometimes it does not format on save, that might explain why I have funky indentation so I have to use `ctrl` + `shift` + `P`

2022-12-06 13:03 UTC, Windvis requested changes

2022-12-06 13:03 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
> +    }
If I understand it correctly we want to set the address to the original address that was selected before entering the manual input mode? If so, I think we already stored it on the `originalContactAdres` property if it was persisted before. If we also want to restore the adres that was selected but wasn't saved before switching to the manual input mode then I would store that on a controller property as well.

If it's for cleanup purposes I think we can simply remove the `currentAddress` record? I'm not sure what all this `filtered` logic is about 😄.

2022-12-06 13:04 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
> +    await this.handleInputToggle();
nitpick, I don't really see the added value of splitting this of in a separate method. If anything I think it makes things harder to follow since the names are similar (but generic). I would move the code of that method back here.

2022-12-06 13:26 UTC, Poltergeistz commented on app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
>          if (adres?.isNew) {
Yes indeed just catched this too.

2022-12-06 13:45 UTC, Poltergeistz commented on app/utils/empty-string-to-null.js
> +export function setEmptyStringsToNull(changeset) {
I have some issues setting up the serializer. I created a file with the logic we need inside `/serializers` but I don't know how to actually apply the logic to the adres model.

2022-12-06 13:58 UTC, Windvis commented on app/utils/empty-string-to-null.js
> +export function setEmptyStringsToNull(changeset) {
If you want to limit the logic to the adres model the file should be at `app/serializers/adres.js`. Ember Data will try to match the serializer name to the model name by default, and fall back to the application serializer.

2022-12-06 14:13 UTC, Poltergeistz commented on app/utils/empty-string-to-null.js
> +export function setEmptyStringsToNull(changeset) {
Ok that what I was doing but maybe my logic inside the `adres.js` is wrong. 

```
  serializeAttribute(snapshot, json, attributeName) {
     if (
       !(typeof attributeName === 'string' && attributeName.trim().length > 0)
     ) {
       attributeName = null;
     }
   }
```

2022-12-06 14:29 UTC, Windvis commented on app/utils/empty-string-to-null.js
> +export function setEmptyStringsToNull(changeset) {
`attributeName` is the actual name of the attribute, so for example `straatNaam`. Not the value stored for that attribute.

You can receive the value from the [snapshot](https://api.emberjs.com/ember-data/4.7/classes/Snapshot/methods/attr?anchor=attr). So `let value = snapshot.attr(key);`

But I'm not sure if you can modify the value in that method so I assume we must tweak the json directly:

```js
  serializeAttribute(snapshot, json, attributeName) {
    super.serializeAttribute(...arguments);

    let attributeValue = snapshot.attr(attributeName);
   
     if (
       typeof attributeValue === 'string' && attributeValue.trim().length === 0)
     ) {
       json.attributes[attributeName] = null;
     }
   }
```

2022-12-08 09:20 UTC, Poltergeistz commented on app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
> +    let fetchAddresses = this.store.peekAll('adres');
I used this to retrieve the dirty address with the filteredAddress but I think I can simply use currentAddress instead ?

2022-12-08 09:20 UTC, Poltergeistz commented on app/controllers/eredienst-mandatenbeheer/mandataris/edit.js
> +    await this.handleInputToggle();
Sure, I can set it back in the `toggleInputMode()` if it's easier to maintain.

2022-12-16 16:08 UTC, cecemel requested changes
Hey, a bit of a stretch to review the code, but I played around.
It gets to do weird things when (errors) when:
- I switch from a previously manual address to a registry addres.
- After this error (i assume broken state) no way to save an address from the registry.

Minor thing, perhaps as a user, if I toggle from fully completed manual address, to an address from the registry, I would not expect the select box to be filled in.

Also note: It seems depending on app-universum 1.5, but now master is on 2.0, perhaps best checking if everything works with that.

2023-01-03 10:19 UTC, Windvis requested changes

2023-01-03 10:20 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/new.js
> +    }
I pushed a commit that removes this.

2023-01-03 10:20 UTC, Windvis commented on app/controllers/eredienst-mandatenbeheer/new.js
> +    if (!(await this.originalContactAdres.adresRegisterUri)) {
Same here.

2023-01-03 10:20 UTC, Windvis commented on app/utils/empty-string-to-null.js
> +export function setEmptyStringsToNull(changeset) {
I'm confused, I think this code is missing from the PR?

2023-01-03 10:22 UTC, Windvis commented
> Minor thing, perhaps as a user, if I toggle from fully completed manual address, to an address from the registry, I would not expect the select box to be filled in.

I think this still is the case at the moment? I think clearing the previous address when switching "modes" will simplify the code a lot and that would also cover that remark.

2023-01-04 08:11 UTC, merged