[Worship-Modules] Add link to Databank Erediensten
lblod/frontend-loket pull request #247
Opened 2023-01-04 15:35 UTC by Poltergeistz

DL-4240

Adding the right access link for databank Erediensten from the right environment.
Adding the module `databank Erediensten` to be only available for users who does have access to Toezicht.

2023-01-04 16:33 UTC, Windvis requested changes

2023-01-04 16:33 UTC, Windvis commented on app/templates/login.hbs
> +            {{#if this.currentSession.canAccessToezicht}}
I believe this will always hide the block since the user isn't logged in on this page. I would either drop the code or always show it.

2023-01-04 16:33 UTC, Windvis commented on config/environment.js
> +    ENV.databankEredienstenUrl =
This will only set the link for local development builds but needs to be configurable from the hosting server, so it needs to be something like this instead:

```js
ENV.worshipDecisionsUrl = '{{WORSHIP_DECISIONS_URL}};
```

The backend can then configure this by setting the `EMBER_WORSHIP_DECISIONS_URL` env variable to a proper value.

2023-01-04 16:33 UTC, Windvis commented on config/environment.js
> +    ENV.databankEredienstenUrl =
I would drop the hardcoded dev and prod links from this file as well.

2023-01-04 16:33 UTC, Windvis commented on app/components/shared/compact-menu.hbs
> +  {{#if this.currentSession.canAccessToezicht}}
instead of using the `canAccessToezicht` directly, it could be nice to create a wrapper getter in the session service that also checks the value of the url.

```suggestion
  {{#if this.currentSession.canAccessWorshipDecisionsDb}}
```

```js
get canAccessWorshipDecisionsDb() {
  return this.canAccessToezicht && !config.worshipDecisionsUrl.startsWith('{{');
}
```
(an actual url check is also an option but might be overkill)

That way the template code makes more sense (using `canAccessToezicht` here looks like a copy pasta mistake if you don't know the ticket history) and it won't be shown if the url isn't configured properly.

2023-01-04 16:33 UTC, Windvis commented on config/environment.js
> +    ENV.databankEredienstenUrl =
I would use English as much as possible. I'm trying hard to Englishify the codebase so it's easier to understand by non-dutch speaking contributors 😄.

2023-01-04 17:19 UTC, Poltergeistz commented on config/environment.js
> +    ENV.databankEredienstenUrl =
Understood :slightly_smiling_face:

2023-01-04 17:20 UTC, Poltergeistz commented on app/templates/login.hbs
> +            {{#if this.currentSession.canAccessToezicht}}
Yes indeed, I think we actually don't need it there since as I understood we have to only show the link to a group of users.

2023-01-05 09:15 UTC, Windvis approved these changes

2023-01-05 09:16 UTC, merged