[Eredienst-mandatenbeheer] View only mode
lblod/frontend-loket pull request #254
Opened 2023-01-11 10:41 UTC by Poltergeistz

In cases where the data is provided by the vendor, the bestuurseenheid (administrative-unit) using this vendor should have a view only mode in loket.

- Adding a new read-only page `details` that shows worship-mandatee's data. a49371dc1c72e40f35f61c772fb2f75b6520e61a
- Adding a new attribute `hasEditRight` in the bestuurseenheid model with `defaultValue: true`. a7185660fe5e58c3c2ddbc6be0ad735d67f0aff2
- Redirecting from `eredienst-mandatenbeheer.mandataris.edit`when the bestuurseenheid has no edit rights. 3e9d2b5f58e54f43dbe47edaf33b8ab171ff4a29
- Overview page `eredienst-mandatenbeheer.mandatarissen` is now checking the `hasEditRight` flag. The `Voeg mandataris toe` button is now hidden & the `bewerk` link in the table is now changed to `bekijk`, the link is now going to the details page when the bestuurseenheid has no edit right. b6fe2b536153d93ec023b409f36c1c04151ce72a

2023-01-12 10:56 UTC, Windvis requested changes

2023-01-12 10:56 UTC, Windvis commented on app/templates/eredienst-mandatenbeheer/mandataris/details.hbs
> +            <AuLabel>Adres</AuLabel>
Nitpick: the semantically correct html structure for this is a [`<dl>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl).

[We already do something like this](https://github.com/lblod/frontend-loket/blob/a417340ecf963d3086039a3d449d043c58556e03/app/components/rdf-form-fields/climate-subsidy-costs-table.hbs#L1-L18) so you can use the same setup I think.

2023-01-12 10:56 UTC, Windvis commented on app/models/bestuurseenheid.js
> +  @attr({ defaultValue: true }) hasEditRight;
Do we know more about how this will actually work in practise?

2023-01-12 11:37 UTC, Poltergeistz commented on app/models/bestuurseenheid.js
> +  @attr({ defaultValue: true }) hasEditRight;
No not yet, I just did this setup for testing.

2023-01-12 12:19 UTC, Poltergeistz commented on app/routes/eredienst-mandatenbeheer/mandataris/edit.js
> +    }
I think I can replace this bestuurseenheid variable above with this.currentSession.group.hasEditRight. Also by overview page you mean `eredienst-mandatenbeheer.mandatarissen` ?

2023-01-12 12:21 UTC, Windvis commented on app/routes/eredienst-mandatenbeheer/mandataris/edit.js
> +    }
Yes 👍

2023-01-12 13:07 UTC, Poltergeistz commented on app/routes/eredienst-mandatenbeheer/mandataris/details.js
> +    });
Yes I realized I can get the contacts relationship from the worship-mandatee.

2023-01-12 16:36 UTC, Poltergeistz commented on app/routes/eredienst-mandatenbeheer/mandataris/edit.js
> +    }
Also did the same for the `/new-person` route

2023-01-12 17:19 UTC, Windvis commented on app/templates/eredienst-mandatenbeheer/mandataris/details.hbs
> +      {{#each @model.contacts as |contact|}}
I don't think this is safe to do. AFAIK the `contacts` relationships contains both the primary and secondary contactpoint linked to this position.

In theory this should print 2 blocks of information. This can be verified by adding a new contactpoint to the position with both primary and secondary information. In that case 2 blocks will be shown, 1 shows the primary information, and the other shows the secondary phone number as the primary phone number.

Something is wrong in our edit logic though, because adding a secondary phone number to an already existing contact doesn't trigger this. I think we forget to update the contacts relationship somewhere in the save flow.

In any case, I would fetch the primary contact point in the route (similar to the edit page) and display that here.

![image](https://user-images.githubusercontent.com/3533236/212135377-7e2132aa-c0ca-4516-8a98-f33a6dfc55b3.png)

2023-01-13 08:57 UTC, Poltergeistz commented on app/templates/eredienst-mandatenbeheer/mandataris/details.hbs
> +  {{/if}}
Okay so I remove the first one. About details page, are we keeping it accessible (I assumed this since if we can edit we could also read but that's just some guessing about rules) ?

Thanks :+1:

2023-01-13 08:58 UTC, Poltergeistz commented on app/templates/eredienst-mandatenbeheer/mandataris/details.hbs
> +      {{#each @model.contacts as |contact|}}
So revert to what was done before ?

2023-01-13 09:03 UTC, Windvis commented on app/templates/eredienst-mandatenbeheer/mandataris/details.hbs
> +  {{/if}}
Yea I would keep it accessible. Other apps that have both a details + edit page usually link to the details page from the overview page table. The details page would then have a "edit button" that links to the edit page. So fairly similar to the alert here, but more intuitive imo. I'm not sure if that's what we want here, but it might just be in the future.

2023-01-13 09:05 UTC, Windvis commented on app/templates/eredienst-mandatenbeheer/mandataris/details.hbs
> +      {{#each @model.contacts as |contact|}}
I'm not sure what was done. But in the edit page we find the ["primaryContactPoint"](https://github.com/lblod/frontend-loket/blob/59a3822be8b0923f3c16e0642dc6dd70be1f1564/app/routes/eredienst-mandatenbeheer/mandataris/edit.js#L21) in the relationship. We should do that here as well so we can display that specific contact instead of looping over the `contacts` relationship. I think that should do what we want.

2023-01-13 09:46 UTC, Windvis commented on app/templates/eredienst-mandatenbeheer/mandataris/details.hbs
> +    <AuAlert @icon="alert-triangle" @skin="warning" @size="small">Deze mandatarisgegevens zijn alleen leesbaar. Je kunt ze niet bewerken.</AuAlert>
Suggested copy from the internal chat:

```suggestion
    <AuAlert @icon="alert-triangle" @skin="warning" @size="small">Deze mandatarisgegevens zijn alleen leesbaar. Je kunt ze niet bewerken want ze worden beheerd door uw softwareleverancier.</AuAlert>
```

2023-01-13 10:04 UTC, Poltergeistz commented on app/templates/eredienst-mandatenbeheer/mandataris/details.hbs
> +    <AuAlert @icon="alert-triangle" @skin="warning" @size="small">Deze mandatarisgegevens zijn alleen leesbaar. Je kunt ze niet bewerken.</AuAlert>
Thanks :slightly_smiling_face:

2023-01-20 16:14 UTC, Windvis reviewed
1 small remark, but other than that it looks good to me 👍. The flags work as expected.

2023-01-20 16:14 UTC, Windvis commented on app/templates/eredienst-mandatenbeheer/mandataris/details.hbs
> +        <AuHr @size="small" />
I would remove this line now.

```suggestion
```

2023-01-23 11:55 UTC, Windvis approved these changes

2023-01-23 11:55 UTC, merged