[needs work] Replace decprected route mixins (ember-simple-auth)
lblod/frontend-loket pull request #36
Opened 2021-02-26 11:58 UTC by aatauil

2021-03-01 13:29 UTC, nvdk commented
:eyes:  following because we will want to do the same in GN

2021-03-01 13:37 UTC, aatauil commented
@nvdk 

The PR has a pretty good explanation on what to do to upgrade
https://github.com/simplabs/ember-simple-auth/pull/2198

The only thing that wasn't very clear was replacing the `ApplicationRouteMixin`. If you want custom logic for e.g. `sessionInvalidated`, you will now have to create a new service that extends from ember-simple-auth's SessionService and there you can overwrite that method with you custom logic :smile:

2021-03-05 12:48 UTC, Windvis requested changes

2021-03-05 12:48 UTC, Windvis commented on app/routes/subsidy/applications/index.js
> +  @service session;
This doesn't seem to be used and the parent handles the check already.

2021-03-05 12:48 UTC, Windvis commented on app/routes/index.js
> +    this.currentSession.load()
Also, I don't think this line needs to be executed if the session is not authenticated, right? So I would swap this below the simple-auth check, and wrap that one in an if?

2021-03-05 12:48 UTC, Windvis commented on app/services/session.js
> +  _loadCurrentSession() {
I think this was not meant to be here?

2021-03-05 12:48 UTC, Windvis commented on app/services/session.js
> +      window.location.replace(logoutUrl);
I think `super.handleInvalidation(logoutUrl)` should work as well and is a nicer solution imo :smile:

2021-03-05 12:48 UTC, Windvis commented on app/services/session.js
> +export default SessionService.extend({
I think a native class should work as well?

2021-03-05 12:48 UTC, Windvis commented on app/routes/index.js
> +    this.currentSession.load()
Actually, I think this line can go since the application route calls it already.

2021-03-05 12:48 UTC, Windvis commented on app/routes/application.js
> -  sessionAuthenticated() {
I think this part is missing after the refactor, or did I overlook it?

2021-03-05 12:53 UTC, Windvis commented
Optional, and it's probably a nice premature DRY refactor :smile: :

Since the session service is already extended, you could override the `requireAuthentication` and `prohibitAuthentication` methods as well and provide default route names.

2021-03-05 12:55 UTC, aatauil commented on app/controllers/subsidy/applications/index.js
> +  @service() session;
Yeah seems like it , the 'Application' probably threw me off guard there

2021-03-05 12:57 UTC, aatauil commented on app/routes/application.js
> -  sessionAuthenticated() {
https://github.com/simplabs/ember-simple-auth/pull/2202#issuecomment-676367340

2021-03-05 13:00 UTC, Windvis commented on app/routes/application.js
> -  sessionAuthenticated() {
Yea sure, but the service has a method you can override, right? Or do you mean that it's no longer needed?

2021-03-05 13:01 UTC, Windvis commented on app/routes/application.js
> -  sessionAuthenticated() {
(Btw, I have no background context on this project, so it might not actually be needed. I just wanted to make sure that it wasn't an oversight :smile:)

2021-03-05 13:02 UTC, aatauil commented on app/routes/index.js
> +    this.currentSession.load()
Yeah that semi-colon is actually important since emacs users are going to be mad at me xd
I think it suffices to place this.currentSession.load() below the requireAuthentication since if the session is not authenticated it will transition before exectuing that line ( I could be wrong though )

2021-03-05 13:04 UTC, Windvis commented on app/routes/index.js
> +    this.currentSession.load()
I think it can be removed actually, since the application route already does it?

2021-03-05 13:05 UTC, aatauil commented on app/routes/switch-login.js
> +    this.session.prohibitAuthentication('login')
Why would you think that maybe? SwitchLogin is it own route so if you would enter the url to that route in your browser then it should not let you visit that route if you are not logged in right?

2021-03-05 13:06 UTC, aatauil commented on app/services/session.js
> +export default SessionService.extend({
yeah but I just didnt want to mess with it right there and then and just focus on the mixins but indeed it has to be converted

2021-03-05 13:07 UTC, aatauil commented on app/services/session.js
> +      window.location.replace(logoutUrl);
Will note it when changing to native class

2021-03-05 13:08 UTC, aatauil commented on app/services/session.js
> +export default SessionService.extend({
this was the most straightforward way of extending the sessionService without renaming it to a different class

2021-03-05 13:10 UTC, aatauil commented on app/routes/index.js
> +    this.currentSession.load()
No it actually gave me a lot of issues, for some reason unless actively calling it in the index route, when you would login using mock-login and it then transitions to index you will see that all modules in the index route will be 'disabled' until you reload the page

2021-03-05 13:11 UTC, aatauil commented on app/routes/subsidy/applications/index.js
> +  @service session;
If not used it should be removed , I left it in since I though it was intentionally placed there for future use or smth? ( in context of authenticatedRouteMixin)

2021-03-05 13:12 UTC, Windvis commented on app/routes/switch-login.js
> +    this.session.prohibitAuthentication('login')
Yea, but in that case it needs to be a `requireAuthentication` call instead, no? I assumed it was similar to the login page. If already logged in, redirect to index.

2021-03-05 13:13 UTC, aatauil commented on app/routes/supervision.js
> +  @service session;
Yes indeed `    this.session.requireAuthentication(transition, 'login');` should be added to beforeModel()

2021-03-05 13:15 UTC, aatauil commented on app/routes/supervision/submissions/index.js
> +    this.session.requireAuthentication(transition, 'login');
I am actually not 100% sure, so testing it without that line seeing if it acts as we want then it can be left out

2021-03-05 13:16 UTC, Windvis commented on app/routes/index.js
> +    this.currentSession.load()
I think that's the thing that the sessionAuthenticated in the Application route did before.

2021-03-05 13:19 UTC, aatauil commented on app/routes/application.js
> -  sessionAuthenticated() {
Actually this might be related to the issue I was having in the index route, so maybe override the method in the SessionService and remove the `this.currentSession.load()` on the index route and see if it will work? sorry I dont remember exactly what I already tried anymore

2021-03-05 13:20 UTC, Windvis commented on app/routes/application.js
> -  sessionAuthenticated() {
Yea I think that should work!

2021-03-05 13:26 UTC, aatauil commented on app/routes/switch-login.js
> +    this.session.prohibitAuthentication('login')
context: (You can only click the 'switchLogin` button from the index route , this to change to another "bestuurseenheid" since a user can belong to multiple bestuurseenheden) now for the moment I dont know exactly what it should do other then logging you in as part of a different bestuurseenheid, thats why I redirect to login. will need more info of Felix for this

2021-03-05 13:34 UTC, aatauil commented
@Windvis Yeah actually that would be nice, but at the same time it should always be flexible to accept other routes in case this is needed in the future ( who knows ). So probable a if (routeSpecified) else (goToDefaultRoute) if possible?

2021-03-08 17:49 UTC, cecemel commented on app/routes/switch-login.js
> +    this.session.prohibitAuthentication('login')
Sorry ignorant person here, but the prohibit wasn't done in the previous version, why would we want this no?

2021-03-08 17:53 UTC, Windvis commented on app/routes/switch-login.js
> +    this.session.prohibitAuthentication('login')
@cecemel The previous version included the `UnauthenticatedRouteMixin` mixin which is the equivalent. I don't think it would redirect to the login route though.

2021-03-12 09:58 UTC, Windvis commented on app/routes/supervision.js
> +  @service session;
Done!

2021-03-12 10:02 UTC, Windvis commented on app/routes/switch-login.js
> +    this.session.prohibitAuthentication('login')
@cecemel I don't know the context of the project so it's hard for me to judge if this change is valid.

The UnauthenticadedRouteMixin redirects a logged in user to the index page. So I _think_ this one needs to be changed to `this.session.prohibitAuthentication('index');`. But the current code will work since the login page also redirects to index when a user is logged in.

2021-03-12 10:02 UTC, Windvis commented on app/services/session.js
> +      window.location.replace(logoutUrl);
Optional change

2021-03-12 10:03 UTC, Windvis commented on app/services/session.js
> +export default SessionService.extend({
Optional change

2021-03-12 10:05 UTC, Windvis commented on app/controllers/subsidy/applications/index.js
> +  @service() session;
Done!

2021-03-12 10:12 UTC, Windvis commented on app/routes/application.js
> -  sessionAuthenticated() {
@aatauil Did you give this a try?

2021-03-12 10:28 UTC, aatauil commented on app/routes/application.js
> -  sessionAuthenticated() {
No it doesnt actually work, suddenly the index page acts up and everything just "breaks"... I thought it would work too tbh

2021-03-12 10:34 UTC, Windvis commented on app/routes/application.js
> -  sessionAuthenticated() {
Ok! In that case: Done!

2021-03-12 10:34 UTC, Windvis commented on app/routes/index.js
> +    this.currentSession.load()
Done! (Related to discussion over here: https://github.com/lblod/frontend-loket/pull/36#discussion_r588268120)

2021-03-12 10:35 UTC, Windvis commented on app/routes/supervision/submissions/index.js
> +    this.session.requireAuthentication(transition, 'login');
Done!

2021-03-12 10:38 UTC, Windvis commented on app/services/session.js
> +  _loadCurrentSession() {
Done!

2021-03-17 15:43 UTC, cecemel commented on app/routes/subsidy/applications/index.js
> +  @service session;
probably copy pasta, should not be there I think

2021-03-17 16:05 UTC, cecemel commented on app/routes/switch-login.js
> +    this.session.prohibitAuthentication('login')
updated to index and tested

2021-03-17 16:28 UTC, cecemel commented on app/routes/application.js
> -  sessionAuthenticated() {
can someone ELI5 here :-) : by what is it replaced now?

2021-03-17 16:40 UTC, cecemel commented
The issue with switch-login, is known on chrome, where a  pop-up is blocked when coming  from a redirect. And will not be tackled here. (Unless someone has an idea) The plan would be to see how we can replace the popup by an iframe.

2021-03-17 16:44 UTC, Windvis commented on app/routes/application.js
> -  sessionAuthenticated() {
By the PR I made (and before that by calling `this.currentSession.load();`).

2021-03-19 15:23 UTC, merged