Add a `subsidies-external` feature flag
lblod/frontend-loket pull request #372
Opened 2024-03-22 09:56 UTC by wolfderechter

## ID
DGS-161

## Description

Add a `subsidies-external` feature flag to quickly change from internal subsidiemodule in loket to external subsidies application redirection.

In the docker-compose.override.yml for production deployment should the following environment variables be added with the final values (TBD):
```
EMBER_SUBSIDIES_URL: "https://......./"
EMBER_FEATURE_SUBSIDIES_EXTERNAL: "false"
```

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## How to test

During development, update the `config/environment.js` environment variables of `subsidies-external` to true/false and `subsidiesUrl` to a new url. The subsidy module should redirect to the url when the feature flag is set to true.

2024-05-08 08:30 UTC, Windvis requested changes

2024-05-08 08:31 UTC, Windvis commented
Looks good, and worked as expected once I configured the environment variables so should be good to merge once the small issues are resolved.

2024-05-08 08:33 UTC, wolfderechter commented on app/routes/subsidies-external-redirect.js
> +        const path = '/subsidy/' + transition.to.params.path;
We are currently keeping the default routes, but have plans to indeed remove the `/subsidy` route one level down if everything works and we have some time

2024-05-08 08:33 UTC, wolfderechter commented on app/components/shared/compact-menu.hbs
> +        Subsidiebeheer
Good idea!

2024-05-08 08:48 UTC, Windvis commented on app/templates/subsidies-external-redirect.hbs
The rename is needed here as well

2024-05-08 08:49 UTC, wolfderechter commented on app/templates/subsidies-external-redirect.hbs
ah yes indeed

2024-05-08 08:52 UTC, Windvis approved these changes

2024-05-08 08:58 UTC, merged

2024-06-19 08:56 UTC, Windvis commented
It seems we forgot to release this. It's part of the [v0.94.0 release](https://github.com/lblod/frontend-loket/blob/development/CHANGELOG.md#v0940-2024-06-19) now.