Fix: subsidies always visible
lblod/frontend-loket pull request #393
Opened 2024-06-24 14:36 UTC by wolfderechter

Since subsidies will move to subsidiepunt as an external app instead of sub-app, we need to always show the subsidies tab

2024-06-24 14:49 UTC, cecemel requested changes

2024-06-24 14:49 UTC, cecemel commented on app/services/current-session.js
> -    if (isFeatureEnabled('subsidies-external')) {
can you keep the toggle logic here please (and also in the templates)? 
- so we keep it consistent
-  also; this will allow us to choose when to deploy loket. This change implies we NEED to deploy loket and subsidiepunt at the same time. I don't want that. I want to first deploy loket; then at own pace do the migration then do the cutover

2024-06-25 09:52 UTC, Windvis commented
If it's a standalone thing it probably makes sense to always hide info about it on the login page?

https://github.com/lblod/frontend-loket/blob/2e054f6892887f607330fd434561a423e82bc43e/app/templates/login.hbs#L300-L330

I think that part needs to be updated to either hide it if the feature is active, or display the `SubsidiePunt` name instead, if we still want to keep the card.

2024-06-25 12:05 UTC, wolfderechter commented
> If it's a standalone thing it probably makes sense to always hide info about it on the login page?
> 
> https://github.com/lblod/frontend-loket/blob/2e054f6892887f607330fd434561a423e82bc43e/app/templates/login.hbs#L300-L330
> 
> I think that part needs to be updated to either hide it if the feature is active, or display the `SubsidiePunt` name instead, if we still want to keep the card.

Marie definitely wants to keep it there, so I have updated it to say 'SubsidiePunt' when needed

2024-06-25 12:10 UTC, Windvis approved these changes

2024-06-25 12:10 UTC, merged