Update subsidy forms initial status
lblod/frontend-loket pull request #56
Opened 2021-08-30 17:12 UTC by claire-lovisa

We use to put new forms in CONCEPT status. We now introduce a new status NEW for more ease when handling tailored data extraction.
A form becomes a CONCEPT when first saved.

2021-08-31 08:28 UTC, cecemel requested changes

2021-08-31 08:28 UTC, cecemel commented on app/controllers/subsidy/applications/edit/step/edit.js
> +      yield this.updateStatus(this.semanticForm, CONCEPT_STATUS);
@claire-lovisa perhaps, for performance, would it be faster to do an if new -> then concept?

2021-08-31 08:28 UTC, cecemel commented on app/controllers/subsidy/applications/edit/step/edit.js
> +      yield this.updateStatus(this.semanticForm, CONCEPT_STATUS);
This is for a later to think about, but i do find it strange now that i think of it, that the status is also managed by subsidy-application-management. I don't remember why.

2021-09-01 08:17 UTC, cecemel requested changes

2021-09-01 08:17 UTC, cecemel commented on app/models/subsidy-application-flow-step.js
> +  @hasMany('file') formSpecifications;
This is rather surprising. In the model I though it would be only one.
https://github.com/lblod/app-digitaal-loket/blob/master/config/resources/master-subsidies-domain.lisp#L104

2021-09-01 08:18 UTC, cecemel commented on app/models/subsidy-application-flow-step.js
> +  @hasMany('file') formSpecifications;
Which I understood, is the flowstep is the concrete instance of the subsidieprocedurestap. But sometimes forms change, without changing the abstract subisdieprocedurestap

2021-09-01 10:12 UTC, cecemel commented on app/models/subsidy-application-flow-step.js
> +  @hasMany('file') formSpecifications;
I reviewed the model, and I think the approach of the first bullet, was the intended path in changes. The fact that flows have been introduced, just complicates everything....

2021-09-02 06:44 UTC, claire-lovisa commented on app/routes/subsidy/applications/edit/step/new.js
> +    form.sources.pushObject(latestSpec);
A set wont work as sources need to be an array I think

2021-09-02 09:19 UTC, merged